# Generated by Django 3.2.13 on 2022-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_payment',
            field=models.CharField(choices=[('готівка', 'готівка'), ('онлайн', 'онлайн')], default='готівка', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('новий', 'новий'), ('виконано', 'виконано'), ('відміна', 'відміна')], default='новий', max_length=200),
        ),
    ]
